name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test -- --ci
        env:
          CI: true
